apiVersion: v1
kind: PersistentVolume
metadata:
   name: mypv1
   labels:
     app: dev
spec:
  capacity:
     storage: 256Mi
  accessModes:
      - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /home/ubuntu/myapp
