kind: VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1
metadata:
  name: vpa
  namespace: <namespace-name> 

spec:
  targetRef:
    name: <deployment-name>
    apiVersion: apps/v1
    kind: Deployment
  updatePolicy:
    updateMode: "Auto"
