kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployment
  namespace: nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /var/www/html
            name: mydata
      volumes:
      - name: mydata
        persistentVolumeClaim:
          claimName: pvc
